const oracledb = require("oracledb");
const dotenv = require("dotenv");
const bcrypt = require("bcryptjs");

dotenv.config();

oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;
oracledb.autoCommit = true;
oracledb.fetchAsString = [oracledb.CLOB];

// Perhatikan: variable dari .env Anda menggunakan DB_USER, DB_PASSWORD, DB_CONNECTION_STRING
const dbConfig = {
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  connectString: process.env.DB_CONNECTION_STRING,
  poolMin: 2,
  poolMax: 10,
  poolIncrement: 1,
};

console.log("🔍 Database Config:", {
  user: dbConfig.user,
  connectString: dbConfig.connectString,
  passwordHidden: "***",
});

let pool = null;

async function initPool() {
  try {
    pool = await oracledb.createPool(dbConfig);
    console.log("✅ Oracle Connection Pool created");

    // Cek versi Oracle
    const conn = await pool.getConnection();
    const result = await conn.execute(
      `SELECT BANNER FROM V$VERSION WHERE ROWNUM = 1`,
    );
    console.log(`📦 Oracle Version: ${result.rows[0].BANNER}`);
    await conn.close();

    // Buat tabel-tabel yang diperlukan
    await initTables();

    return pool;
  } catch (err) {
    console.error("❌ Oracle Connection Error:", err.message);
    throw err;
  }
}

async function initTables() {
  const conn = await pool.getConnection();

  try {
    // 1. Tabel admin_users
    await conn.execute(`
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE admin_users (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username VARCHAR2(50) UNIQUE NOT NULL,
                        password VARCHAR2(255) NOT NULL,
                        role VARCHAR2(20) DEFAULT ''admin'',
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                ';
                EXCEPTION WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        `);
    console.log("📋 Table admin_users checked");

    // 2. Tabel activity_logs
    await conn.execute(`
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE activity_logs (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        admin_id NUMBER,
                        role VARCHAR2(20),
                        method VARCHAR2(10),
                        endpoint VARCHAR2(255),
                        action VARCHAR2(100),
                        status NUMBER,
                        ip_address VARCHAR2(50),
                        user_agent VARCHAR2(500),
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                ';
                EXCEPTION WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        `);
    console.log("📋 Table activity_logs checked");

    // 3. Tabel agents
    await conn.execute(`
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE agents (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nama VARCHAR2(100) NOT NULL,
                        nama_agen VARCHAR2(100) NOT NULL,
                        email VARCHAR2(100) UNIQUE NOT NULL,
                        password VARCHAR2(255) NOT NULL,
                        no_hp VARCHAR2(20),
                        alamat VARCHAR2(255),
                        kota VARCHAR2(50),
                        provinsi VARCHAR2(50),
                        jenis_usaha VARCHAR2(100),
                        status VARCHAR2(20) DEFAULT ''pending'',
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                ';
                EXCEPTION WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        `);
    console.log("📋 Table agents checked");

    // 4. Cek dan buat admin default jika belum ada
    const adminCheck = await conn.execute(
      `SELECT COUNT(*) as total FROM admin_users WHERE username = :username`,
      { username: process.env.ADMIN_USERNAME },
    );

    if (adminCheck.rows[0].TOTAL === 0) {
      const hashedPassword = await bcrypt.hash(process.env.ADMIN_PASSWORD, 10);
      await conn.execute(
        `INSERT INTO admin_users (username, password, role) 
                 VALUES (:username, :password, 'superadmin')`,
        {
          username: process.env.ADMIN_USERNAME,
          password: hashedPassword,
        },
      );
      console.log("✅ Default admin created");
    }

    await conn.commit();
  } catch (err) {
    // Jangan throw error jika privilege issue - tabel mungkin sudah ada
    if (err.errorNum && err.errorNum === 1950) {
      console.warn(
        "⚠️  Skipping table creation due to privilege restrictions (tables may already exist)",
      );
    } else {
      console.error("Error creating tables:", err.message);
    }
  } finally {
    await conn.close();
  }
}

async function query(sql, binds = {}) {
  let conn;
  try {
    conn = await pool.getConnection();
    const result = await conn.execute(sql, binds);
    return result.rows;
  } catch (err) {
    console.error("Query Error:", err.message);
    throw err;
  } finally {
    if (conn) await conn.close();
  }
}

async function execute(sql, binds = {}) {
  let conn;
  try {
    conn = await pool.getConnection();
    const result = await conn.execute(sql, binds, { autoCommit: true });
    return result;
  } catch (err) {
    console.error("Execute Error:", err.message);
    throw err;
  } finally {
    if (conn) await conn.close();
  }
}

async function getOne(sql, binds = {}) {
  const rows = await query(sql, binds);
  return rows.length > 0 ? rows[0] : null;
}

module.exports = {
  initPool,
  query,
  execute,
  getOne,
  pool,
};
